services:
  - type: web
    name: youtube-downloader
    env: docker
    plan: free
    region: ohio
    dockerContext: .
    dockerpath: Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
